include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.mocks.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "lib/generated_plugin_registrant.dart"
