include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

linter:
  rules:
    - prefer_relative_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - '**.mocks.dart'
    - '**.gr.dart'
    - '**.config.dart'
    - 'lib/generated_plugin_registrant.dart'
