include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.mocks.dart"
    - "**.gr.dart"
    - "**.config.dart"
    - "lib/generated_plugin_registrant.dart"
