name: silgam
description: Silgam

publish_to: 'none'
version: 0.2.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  just_audio: ^0.9.18
  firebase_core: ^1.10.2
  firebase_analytics: ^9.0.0-dev.4
  firebase_crashlytics: ^2.4.0
  firebase_messaging: ^11.2.0
  firebase_auth: ^3.3.3
  firebase_storage: ^10.2.3
  cloud_firestore: ^3.1.4
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^4.0.1
  sign_in_with_apple: ^3.3.0
  wakelock: ^0.6.1+1
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  uuid: ^3.0.5
  photo_view: ^0.13.0
  package_info_plus: ^1.3.0
  in_app_review: ^2.0.3
  url_launcher: ^6.0.17
  crypto: ^3.0.1
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  build_runner: ^2.1.5
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/announcements/
    - assets/app_icon/
    - assets/noises/
  fonts:
    - family: NanumSquare
      fonts:
        - asset: fonts/NanumSquareL.otf
        - asset: fonts/NanumSquareR.otf
        - asset: fonts/NanumSquareB.otf
        - asset: fonts/NanumSquareEB.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/app_icon/app_icon_responsive.png"

flutter_native_splash:
  background_image: assets/splash_background.png
  image: assets/app_icon/app_icon_transparent.png
