name: silgam
description: Silgam

publish_to: 'none'
version: 0.3.4+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  just_audio: ^0.9.20
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_crashlytics: ^2.5.3
  firebase_messaging: ^11.2.10
  firebase_auth: ^3.3.10
  firebase_storage: ^10.2.9
  cloud_firestore: ^3.1.10
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1
  sign_in_with_apple: ^3.3.0
  wakelock: ^0.6.1+2
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  package_info_plus: ^1.4.0
  in_app_review: ^2.0.4
  url_launcher: ^6.0.20
  crypto: ^3.0.1
  shared_preferences: ^2.0.13
  kakao_flutter_sdk: ^1.0.0
  http: ^0.13.4
  rich_text_controller: ^1.4.0
  screenshot: ^1.2.3
  path_provider: ^2.0.9
  share_plus: ^4.0.3
  image_gallery_saver: ^1.7.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_datetime_picker:
    git:
      url: git://github.com/Realank/flutter_datetime_picker.git
      ref: eb66486c47d50bf550950c196486121ffcea8885
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.2+1
  build_runner: ^2.1.7
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/announcements/
    - assets/app_icon/
  #    - assets/noises/
  fonts:
    - family: NanumSquare
      fonts:
        - asset: fonts/NanumSquareL.otf
        - asset: fonts/NanumSquareR.otf
        - asset: fonts/NanumSquareB.otf
        - asset: fonts/NanumSquareEB.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/app_icon/app_icon_responsive.png"

flutter_native_splash:
  background_image: assets/splash_background.png
  image: assets/app_icon/app_icon_transparent.png
