name: silgam
description: Silgam

publish_to: 'none'
version: 1.7.1+96

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  just_audio:
    git:
      url: https://github.com/silgam/just_audio
      path: just_audio
      ref: fix/memory-leak
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.5
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.1
  sign_in_with_apple: ^4.1.0
  image_picker: ^0.8.4+11
  intl: any
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  package_info_plus: ^4.1.0
  in_app_review: ^2.0.4
  url_launcher: ^6.0.20
  crypto: ^3.0.1
  shared_preferences: ^2.1.1
  kakao_flutter_sdk: ^1.4.3
  http: ^0.13.4
  rich_text_controller: ^1.4.0
  screenshot: ^2.1.0
  path_provider: ^2.0.9
  share_plus: ^4.0.3
  image_gallery_saver: ^1.7.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  google_mobile_ads: ^2.3.0
  mixpanel_flutter: ^2.0.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  freezed_annotation: ^2.1.0
  fl_chart: ^0.63.0
  photo_view: ^0.14.0
  dio: ^5.1.2
  audio_session: ^0.1.10
  cached_network_image: ^3.3.1
  in_app_purchase: ^3.1.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  in_app_purchase_storekit: ^0.3.4+1
  flutter_easyloading: ^3.0.5
  multiple_result: ^4.0.0
  collection: ^1.16.0
  webview_flutter: ^4.2.0
  dotted_line: ^3.1.0
  flutter_heatmap_calendar:
    git:
      url: https://github.com/silgam/flutter_heatmap_calendar.git
  connectivity_plus: ^3.0.3
  wakelock_plus: ^1.1.1
  flutter_localizations:
    sdk: flutter
  firebase_database: ^10.2.7
  visibility_detector: ^0.3.3
  flutter_form_builder: 9.2.1
  form_builder_validators: ^9.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.2+1
  build_runner: ^2.1.7
  json_serializable: ^6.1.5
  freezed: ^2.1.1
  injectable_generator: ^2.1.3
  retrofit_generator: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/announcements/
    - assets/app_icon/
    - assets/noises/
  fonts:
    - family: NanumSquare
      fonts:
        - asset: fonts/NanumSquareL.otf
        - asset: fonts/NanumSquareR.otf
        - asset: fonts/NanumSquareB.otf
        - asset: fonts/NanumSquareEB.otf
    - family: EstablishRetrosans
      fonts:
        - asset: fonts/EstablishRetrosans.otf

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app_icon/app_icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/app_icon/app_icon_responsive.png'

flutter_native_splash:
  background_image: assets/splash_background.png
  image: assets/app_icon/app_icon_transparent.png
  android_12:
    image: assets/app_icon/app_icon_transparent_1152.png
    color: '#283593'
