name: silgam
description: Silgam

publish_to: 'none'
version: 0.1.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  just_audio: ^0.9.18
  firebase_core: ^1.10.2
  firebase_analytics: ^9.0.0-dev.4
  firebase_crashlytics: ^2.4.0
  firebase_messaging: ^11.2.0
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.7
  wakelock: ^0.5.6
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/announcements/
    - assets/app_icon/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: fonts/NotoSansKR-Black.otf
          weight: 900
    - family: NanumMyeongjo
      fonts:
        - asset: fonts/NanumMyeongjo-ExtraBold.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/app_icon/app_icon_responsive.png"

flutter_native_splash:
  background_image: assets/splash_background.png
  image: assets/app_icon/app_icon_transparent.png
