include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 100

linter:
  rules:
    - prefer_relative_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
