name: ui
publish_to: none

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
